name: Andrew Yang
favicon: null
layout_spectrum: 0
typography_spectrum: 0.19255
title: Andrew Yang
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#323232'
    - '#fcfcfc'
    - '#dbe2e6'
    - '#adbac0'
    - '#707a80'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
