name: Andrew Yang
favicon: null
layout_spectrum: 0.33733429783023894
typography_spectrum: 0.15703816409222782
title: 'Think Big, Start Small'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.47033035615459085
  lightness: 0.23139750096015632
  saturation: 0.2160416345577687
  rhythmicContrast: 0.6526284089777619
purpose: []
